# Generated by Django 4.1.7 on 2023-03-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
